Insert into tb_cliente 
(cod_cliente, cliente_titular, nome, telefone, endereco, cidade, uf, email)
values 
(1,null,'Joaquim Maria Machado de Assis ','32-2113-6009','Rua Rio de Janeiro, 1839','Bicas','MG',null),
(2,null,'João Paulo Emílio Cristóvão dos Santos Coelho Barreto','32-2431-6112','Rua Rio de Janeiro, 1881/201','Bicas','MG',null),
(3,2,'Afonso Henriques de Lima Barreto ',null,'Rua Rio de Janeiro, 1881/301','Bicas','MG',null),
(4,null,'Júlia Valentim da Silveira Lopes de Almeida ',null,'Rua Rio de Janeiro, 1934','Bicas','MG',null),
(5,null,'João Simões Lopes Neto ',null,'Rua Pelotas, 1865','Bicas','MG',null),
(6,null,'Jose Bento Renato Monteiro Lobato ',null,'Rua Taubaté, 1882','Guaratinguetá','SP',null),
(7,null,'Antônio Castilho de Alcântara Machado d''Oliveira',null,'Av, São Paulo, 1901','Bicas','MG',null),
(8,null,'Graciliano Ramos de Oliveira ',null,'Rua Qebrangulo, 1892','Queluz','SP',null),
(9,null,'Eddy Dias da Cruz ','32-2432-9877','Rua Rio de Janeiro, 1907','Bicas','MG',null),
(10,null,'Aníbal Monteiro Machado ',null,'Rua Sabará, 1884','Bicas','MG',null),
(11,null,'Mário Raul de Morais Andrade ',null,'Av, São Paulo, 1893','Bicas','MG',null),
(12,null,'Bernardo Élis Fleury de Campos Curado ',null,'Rua Corumbá de Goiás, 1915/201','Três Rios','RJ',null),
(13,null,'Carlos Drummond de Andrade ','32-2655-9711','Rua Itabira, 1902','Bicas','MG',null),
(14,null,'Osman da Costa Lins ',null,'Rua Vitória de Santo Antão, 1924','Vitória','ES',null),
(15,null,'Murilo Eugênio Rubião ','32-2761-9891','Rua Carmo de Minas, 1916','Juiz de Fora','MG',null),
(16,null,'Samuel Rawet',null,'Av, Polônia, 1929','Petrópolis','RJ',null),
(17,null,'Rubem Braga ',null,'Rua Cachoeiro de Itapemirim, 1913','S,J, Nepomucemo','MG',null),
(18,null,'Rachel de Queiroz',null,'Av, Fortaleza, 1910','S,J, Nepomucemo','MG',null),
(19,null,'Érico Lopes Veríssimo',null,'Rua Cruz Alta, 1905','S,J, Nepomucemo','MG',null),
(21,null,'José J, Veiga',null,'Rua Corumbá de Goiás, 1915/301','Três Rios','RJ',null),
(22,null,'José Rubem Fonseca ',null,'Av, Juiz de Fora, 1911','Bicas','MG',null),
(20,22,'Dinah Silveira de Queiroz',null,'Av, São Paulo, 1911','Bicas','MG',null),
(23,16,'Clarice Lispector',null,'Av, Ucrânia, 1920','Petrópolis','RJ',null),
(24,null,'Otto de Oliveira Lara Resende ',null,'Rua São João del Rey, 1922','Juiz de Fora','MG',null),
(25,null,'Orígenes Lessa ',null,'Rua Lençóis Paulistas, 1903','Bicas','MG',null),
(26,null,'Lygia Fagundes Telles ',null,'Av, São Paulo, 1923','Bicas','MG',null),
(27,2,'Fernando Tavares Sabino ',null,'Av, Belo Horizone, 1923','Bicas','MG',null),
(28,null,'Dalton Jérson Trevisan ','32-2512-0808','Rua Curitiba, 1925','Bicas','MG',null),
(29,null,'Carlos Heitor Cony ',null,'Rua Rio de Janeiro, 1926','Bicas','MG',null),
(30,19,'Roberto Francis Drummond ','32-2114-9587','Rua Ferros, 1933','S,J, Nepomucemo','MG',null),
(31,null,'Nélida Cuiñas Piñon ',null,'Rua Rio de Janeiro, 1937','Bicas','MG',null),
(32,null,'João Ubaldo Osório Pimentel Ribeiro ','32-2661-7755','Rua Itaparica, 1923','Juiz de Fora','MG',null),
(33,9,'Sérgio Sant''Anna ',null,'Rua Rio de Janeiro, 1941','Bicas','MG',null);
